### ISSUE TITLE
Add documentation to Back End files.

### ISSUE THREAD

**Issue by CharlieMorocz** [rumncoke-ai/Team-NLU-Voiceflow-Extension#17]
The Back End needs to have documents explaining what each file is and how the functions within them work. All files should be readable by an outsider such that they can have at least a simplified understanding of the code's functionality.

**Comment by rumncoke-ai** [comment]
Added documentation to all methods

Important methods received a special documentation that specify what the method does and for certain methods broke down the return statement for project members to better understand the methods. 

EXAMPLE: 

/**
     * Method getJSONContent.
     *
     * @return Return all transcript data from attached to the chatbot from the set apiKey and Version ID
     *
     * Data is cleaned and exibits both messages and intents specific format includes:
     *     Outermost layer: Stores overall result for all transcripts.
     *     Middle Layer: Each element is a full transcript.
     *     Inner layer: Each element is a turn.
     *     String: either a user intent or bot message in the format "message: " + the actual message (same for intents)."
     */
