### ISSUE TITLE
Rumaisa and Molly implement a feature on the front end.

### ISSUE THREAD

**Issue by rumncoke-ai** [rumncoke-ai/Team-NLU-Voiceflow-Extension#30]
It is important that we switch up roles and everyone works on both frontend and backend code. Given that Molly and Rumaisa have not implemented a frontend feature yet, we should do that.

**Comment by rumncoke-ai** [comment]
I have adjusted out main page and upload page, and after sitting and talking with Martin have gained a better understanding of using React

**Comment by molplu** [comment]
I implemented the end page. After working with Charlie, I have a better understanding of the different components of our react frontend.
