### ISSUE TITLE
Ensure every member of the team is a contributor on both repos.

### ISSUE THREAD

**Issue by molplu** [rumncoke-ai/Team-NLU-Voiceflow-Extension#33]
Once every member is a contributor on both repos, we should ensure everyone has contributed to both frontend and backend. See tasks "Molly and Rumaisa..." and "Kareem and Charlie...".

**Comment by molplu** [comment]
We just need to merge my PR to the main branch and we will all be contributors on both repos.

**Comment by rumncoke-ai** [comment]
Good job everyone!! All 5 of us are now contributors to the both repositories
