### ISSUE TITLE
Implement testing for both calls to Voiceflow's API.

### ISSUE THREAD

**Issue by molplu** [rumncoke-ai/Team-NLU-Voiceflow-Extension#35]
**I'm submitting a ...** 

- [ ] Bug Report
- [x] Feature Request

 **Which repositories are involved in this issue?**

- [ ] **[Front-end](https://github.com/KareemSalem7/voice-flow)**
- [x] **[Back-end](https://github.com/rumncoke-ai/Team-NLU-Voiceflow-Extension)**

<details>
 <summary><h1>FEATURE REQUEST</h1></summary>

<b>Description of Feature:</b>

We should have tests for any code which is accessing the Voiceflow API that ensure a successful connection, correct data retrieving functionality, and proper return formatting. Try to get at least 80% coverage (we can discuss that number as a team). 

**Motivation:**

As so much of our project is reliant on these calls to the API, we want to make sure that we are successfully identifying and subsequently resolving any issues with this functionality.

**Related Files and Code:**

*[TranscriptService.java](https://github.com/rumncoke-ai/Team-NLU-Voiceflow-Extension/blob/main/transcript/src/main/java/com/transcriptanalyzer/transcript/User_Requests_Intents/Service/TranscriptService.java)
*[UserAPIRequestModel.java](https://github.com/rumncoke-ai/Team-NLU-Voiceflow-Extension/blob/main/transcript/src/main/java/com/transcriptanalyzer/transcript/UserAPIRequestModel.java)
*[createBlocksVoiceflow.java](https://github.com/rumncoke-ai/Team-NLU-Voiceflow-Extension/blob/voiceflow-API-blocks/transcript/src/main/java/com/transcriptanalyzer/transcript/Service/createBlocksVoiceflow.java)
*[getToken.java](https://github.com/rumncoke-ai/Team-NLU-Voiceflow-Extension/blob/voiceflow-API-blocks/transcript/src/main/java/com/transcriptanalyzer/transcript/Service/getToken.java)

</details>

<details>
 <summary><h1>BUG REPORT</h1></summary>

<b>Current behavior:</b>

**Expected Behaviour:**

**Steps to Reproduce:**

**Related Code & Files:**

* List files here

```
And any specific lines of code if applicable.
```

* Rinse

```
And repeat!
```
</details>

<h2>(Optional) Useful External Resources:</h2>

* N/A

Note from Molly: How can we test API calls? What is the best way to do that?

**Comment by rumncoke-ai** [comment]
We have completed some basic testing for both calls to the Voiceflow API. 

I tested whether the IOexception was working properly -> If given an invalid information, error message should be returned
